// <auto-generated />
namespace JiraSuite.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createemptystringparamatertoavoidnullexceptionsfornsobjs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createemptystringparamatertoavoidnullexceptionsfornsobjs));
        
        string IMigrationMetadata.Id
        {
            get { return "201611042045424_Create empty string paramater to avoid null exceptions for ns objs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
